# Generated by Django 5.0.2 on 2024-03-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_customer_date_created_alter_order_date_created_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("Indoor", "Indoor"), ("Outdoor", "Outdoor")],
                max_length=200,
                null=True,
            ),
        ),
    ]
