# Generated by Django 5.0.2 on 2024-05-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customer_user_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
